/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wudongchuan_myapplication_SecondLib */

#ifndef _Included_com_example_wudongchuan_myapplication_SecondLib
#define _Included_com_example_wudongchuan_myapplication_SecondLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wudongchuan_myapplication_SecondLib
 * Method:    intMethod
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_wudongchuan_myapplication_SecondLib_intMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_wudongchuan_myapplication_SecondLib
 * Method:    stringMethod
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_wudongchuan_myapplication_SecondLib_stringMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_example_wudongchuan_myapplication_SecondLib
 * Method:    sumMethod
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_wudongchuan_myapplication_SecondLib_sumMethod
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
